### ISSUE TITLE
Obsqr taken down from Play Store for some reason

### ISSUE THREAD

**Issue by TacoTheDank** [trikita/obsqr#11]
Going to "https://play.google.com/store/apps/details?id=trikita.obsqr" turns up "We're sorry, the requested URL was not found on this server." (Same with https://play.google.com/store/apps/details?id=trikita.googleplay.obsqr)

Why was Obsqr taken down from the Play Store? :/

(Here is the Obsqr APK that comes from the Play Store btw, for those who might be looking for it)
(the APK is in the zip file, I can't upload the APK by itself lol)

[Obsqr[GPlay(taken down)]_v3.0(16){trikita.obsqr}.zip](https://github.com/trikita/obsqr/files/1981394/Obsqr.GPlay.taken.down._v3.0.16.trikita.obsqr.zip)

**Comment by abdulmalikkhan655** [comment]
scamer @TacoTheDank becarefull

**Comment by TacoTheDank** [comment]
lmfao @abdulmalikkhan655 now you're trying to throw shade at me because i've exposed your stupid ass stealing icons from flaticons to try to gain crypto from utopian.io

dude why do you even try

**Comment by abdulmalikkhan655** [comment]
you are also buig scameer basted mother fucker

**Comment by abdulmalikkhan655** [comment]
i will fuck you you are scamer

**Comment by TacoTheDank** [comment]
lmfao keep trying bud

**Comment by TacoTheDank** [comment]
i dont even sell shit

**Comment by TacoTheDank** [comment]
and it's "scammer", at least spell it right you shitrag

**Comment by abdulmalikkhan655** [comment]
sir @trikita becarefull from @TacoTheDank  this guyz scamer don,t trust him

**Comment by abdulmalikkhan655** [comment]
scammer

**Comment by TacoTheDank** [comment]
repeating shit gets you nowhere in an argument

**Comment by abdulmalikkhan655** [comment]
scammer

**Comment by TacoTheDank** [comment]
k

**Comment by TacoTheDank** [comment]
ugh

**Comment by appel** [comment]
It seems it's still available via F-Droid, for those wandering in from Google looking for it:
https://f-droid.org/en/packages/trikita.obsqr/
